spring:
  datasource:
    url: jdbc:mysql://localhost:3306/player?useSSL=false&serverTimezone=UTC
    username: root
    password: XDDAW(21)
    driver-class-name: com.mysql.cj.jdbc.Driver
jpa:
  hibernate:
    ddl-auto: update
  show-sql: true
  properties:
    hibernate:
      dialect: org.hibernate.dialect.MySQL8Dialect
  hikari:
    maximum-pool-size: 10
